name: check eslint
on: 
  push:
    branches:
      - adding-issue
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Nodejs and npm
      uses: actions/setup-node@v2
      with:
        node-version: "14"
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx