name: check eslint
on: 
 push:
  branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx
