name: Create docker image

on: 
  push:
    branches:
      - action-for-docker-compose

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: sudo-bot/action-docker-compose@latest
        with:
        # https://docs.docker.com/compose/reference/overview/
          cli-args: "up"
      # - uses: isbang/compose-action@v1.4.1
      #   with:
      #     compose-file: "docker-compose.yml"
      #     up-flags: "--build"
      #     services: |
      #       helloworld2
