name: Create docker image

on: 
  push:
    branches:
      - action-for-docker-compose

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the stack
        run: docker-compose up -d
      # - uses: isbang/compose-action@v1.4.1
      #   with:
      #     compose-file: "docker-compose.yml"
      #     up-flags: --build
